steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://flask_ops']
  
  - name: 'python'
    args: ['touch', 'test.txt', '&&', 'ls']
    env:
        - 'FLASK_APP=${_FLASK_APP}'