steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://flask_ops']
    
  - name: 'python'
    args: ['python3', '-m', 'venv', 'venv']
    
  - name: 'ubuntu'
    args: ['venv/Scripts/activate']
  
  - name: 'python'
    args: ['pip3', 'install', 'flask']
    
  - name: 'ubuntu'
    args: ['export', 'FLASK_APP=hello_world.py']
    
  - name: 'python'
    args: ['flask', 'run', '--host', '0.0.0.0']