steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://flask_ops']
    
  - name: 'python'
    args: ['python3', '-m', 'venv', 'venv']
    
  - name: 'cd'
    args: ['venv/Scripts']
  
  - name: 'activate'
  
  - name: 'cd'
    args: ['../../']
  
  - name: 'python'
    args: ['pip3', 'install', 'flask']
    
  - name: 'set'
    args: ['FLASK_APP=hello_world.py']
    
  - name: 'flask'
    args: ['run', '--host', '0.0.0.0']