steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://flask_ops']
  
  - name: 'python'
    args: ['pip3', 'install', 'flask']
    
  - name: 'ubuntu'
    args: ['echo', 'hello there!']
    env:
        - 'FLASK_APP=${_FLASK_APP}'
    
  - name: 'python'
    args: ['flask', 'run', '--host', '0.0.0.0']