steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", ".", "gs://flask_ops"]
    
  - name: docker
    args: ["login", "-u", "rdefente", "-p", "b33pb00p"]
    
  - name: python3
    args: ["-m", "venv", "venv"]
    
  - name: cd
    args: ["venv/Scripts"]
  
  - name: activate
  
  - name: cd
    args: ["../../"]
  
  - name: pip
    args: ["install", "flask"]
    
  - name: set
    args: ["FLASK_APP=hello_world.py"]
    
  - name: flask
    args: ["run", "--host", "0.0.0.0"]