steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://flask_ops']
  
  - name: 'python'
    args: ['pip3', 'install', 'flask']
    
  - name: 'ubuntu'
    args: ['export', 'FLASK_APP=/workspace/hello_world.py']
    
  - name: 'python'
    args: ['flask', 'run', '--host', '0.0.0.0']